name: 'Run shfmt with reviewdog'
description: '🐶 Run shfmt with reviewdog on pull requests to improve code review experience.'
author: 'haya14busa'
inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    default: '${{ github.token }}'
  workdir:
    description: 'Working directory relative to the root directory.'
    default: '.'
  ### Flags for reviewdog ###
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'error'
  filter_mode:
    description: |
      Filtering mode for the reviewdog command [added,diff_context,file,nofilter].
      Default is added.
    default: 'added'
  fail_on_error:
    description: |
      Exit code for reviewdog when errors are found [true,false]
      Default is `false`.
    default: 'false'
  reviewdog_flags:
    description: 'Additional reviewdog flags'
    default: ''
  ### Flags for shfmt ###
  shfmt_flags:
    description: 'flags for shfmt'
    default: '-i 2 -ci'
runs:
  using: 'composite'
  steps:
    - run: $GITHUB_ACTION_PATH/script.sh
      shell: bash
      env:
        INPUT_SHFMT_FLAGS: ${{ inputs.shfmt_flags }}
    - uses: reviewdog/action-suggester@87d77977e46ff1b90917c96ee550ac2e297c71a2 # v1.20.1
      with:
        tool_name: shfmt
        github_token: ${{ inputs.github_token }}
        level: ${{ inputs.level }}
        filter_mode: ${{ inputs.filter_mode }}
        fail_on_error: ${{ inputs.fail_on_error }}
        reviewdog_flags: ${{ inputs.reviewdog_flags }}

# Ref: https://haya14busa.github.io/github-action-brandings/
branding:
  icon: 'check'
  color: 'blue'
